# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d1c05f350b42203470acdf4858a4c588472ad3b94b075724768ebdc05969b76d7b069f3d51b23f549bdc60d047bc8128134d7abfec5d79b07580f8a0209419

test:
  secret_key_base: 292b5586da1354f8b3749ccbcebe5b4b643eb8b47e20b042328a934c4f5f8804201194be922a90b530ad99e3fb7a1d0eff8ea6c88e16904d57ed60342df14fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
